bundler_args: --without development production
language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
env:
  - DB=sqlite
script:
  - bundle exec rake db:test:prepare
  - rake db:migrate RAILS_ENV=test
  - bundle exec rspec spec
before_script:
  - "cp ./config/database.travis.yml ./config/database.yml"
after_failure:
  - "cat ./config/database.yml"
  - "cat ./db/schema.rb"
