bundler_args: --without development
language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - ruby-head
before_script:
  - "cp config/database.travis.yml config/database.yml"
matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
script: bundle exec rspec spec
